version: 2.1
orbs:
  docker: circleci/docker@0.5.17
executors:
   cci-toolbox-java11:
     docker:
       - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
         auth:
           username: _json_key
           password: $DOCKER_PASSWORD
     environment:
       DEBIAN_FRONTEND: "noninteractive"
       MAVEN_OPTS: -Xmx3G
jobs:
  build:
    executor: cci-toolbox-java11
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn install -s /tools/m2/settings.xml
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
    - persist_to_workspace:
        root: ~/project
        paths:
        - target
        - pom.xml
        - .circleci
        - Dockerfile
workflows:
  version: 2.1
  build_test_deploy:
    jobs:
    - build:
        name: build
        context: org-carbon
    - docker/publish:
        pre-steps:
          - attach_workspace:
              at: ~/project
        requires:
          - build
        name: push-release
        image: asag
        registry: $DOCKER_REGISTRY
        tag: 0.0.2
        deploy: true
        context: global
        filters:
          branches:
            only: master
