version: 2.1
orbs:
  docker: circleci/docker@0.5.17
executors:
   cci-toolbox-java11:
     docker:
       - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
         auth:
           username: _json_key
           password: $DOCKER_PASSWORD
     environment:
       DEBIAN_FRONTEND: "noninteractive"
       MAVEN_OPTS: -Xmx3G
aliases:
  - &docker-build-and-push
    name: Docker build and push
    command: |
      IMAGE="eu.gcr.io/entur-system-1287/${CIRCLE_PROJECT_REPONAME}"
      echo "Image: ${IMAGE}"
      docker build -t $IMAGE .
      docker tag $IMAGE "${IMAGE}":"latest"
      docker push $IMAGE
  - &docker-login
    name: Docker login
    command: |
      docker login -u "_json_key" -p "${DOCKER_PASSWORD}" eu.gcr.io
  - &GCP-auth
    name: GCP Authenticate
    command: |
      echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
      /tools/gcp_authenticate.sh
jobs:
  build:
    executor: cci-toolbox-java11
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn install -s /tools/m2/settings.xml
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
    - persist_to_workspace:
        root: ~/project
        paths:
        - target
        - pom.xml
        - .circleci
        - Dockerfile
  docker-publish:
    executor: cci-toolbox-java11
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *GCP-auth
      - run: *docker-login
      - run: *docker-build-and-push
workflows:
  version: 2.1
  build_test_deploy:
    jobs:
    - build:
        name: build
        context: org-carbon
    - docker-publish:
        context: org-carbon
        requires:
          - build
        filters:
          branches:
            only: master
